force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <nameField>
        <label>Transporteur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteur</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Transporteur__c/fields/Delai__c.field-meta.xml
<CustomField>
    <fullName>Delai__c</fullName>
    <label>Delai</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transporteur__c/fields/Prix__c.field-meta.xml
<CustomField>
    <fullName>Prix__c</fullName>
    <label>Prix</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transporteur__c/fields/Type_Client__c.field-meta.xml
<CustomField>
    <fullName>Type_Client__c</fullName>
    <label>Type Client</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Particulier</fullName>
            </value>
            <value>
                <fullName>Professionnel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransporteurPrix__c/TransporteurPrix__c.object-meta.xml
<CustomObject>
    <label>Transporteur Prix</label>
    <nameField>
        <displayFormat>TP-{0000}</displayFormat>
        <label>TransporteurPrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteur Prix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TransporteurPrix__c/fields/D_lai_de_Livraison_jours__c.field-meta.xml
<CustomField>
    <fullName>D_lai_de_Livraison_jours__c</fullName>
    <label>Délai de Livraison (jours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TransporteurPrix__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
            <value>
                <fullName>Suisse</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransporteurPrix__c/fields/Tarifs__c.field-meta.xml
<CustomField>
    <fullName>Tarifs__c</fullName>
    <label>Tarifs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TransporteurPrix__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Transporteur Prix</relationshipLabel>
    <relationshipName>Transporteur_Prix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TransporteurService.cls
public with sharing class TransporteurService {

    public static Transporteur__c getBestTransporteur(String pays, String critere){

        /*List<Transporteur__c> transporteurs = [
            SELECT Name, Prix__c, Delai__c
            FROM Transporteur__c
            WHERE Pays__c = :pays
        ];

        Transporteur__c best;

        for(Transporteur__c t : transporteurs){

            if(best == null){
                best = t;
            } else {

                if(critere == 'Prix' && t.Prix__c < best.Prix__c){
                    best = t;
                }

                if(critere == 'Delai' && t.Delai__c < best.Delai__c){
                    best = t;
                }
            }
        }*/

        return null;
    }
    public static list<TransporteurPrix__c> getAllTransporteurs(String pays,String orderId){
        Order acc=[Select id,Account.Type_Client__c from Order where Id=:orderId limit 1];
        return [SELECT Name, Tarifs__c, Pays__c,D_lai_de_Livraison_jours__c,Transporteur__r.Name,Transporteur__r.Type_Client__c FROM TransporteurPrix__c WHERE Pays__c = :pays AND Transporteur__r.Type_Client__c INCLUDES(:acc.Account.Type_Client__c) ORDER BY Tarifs__c,D_lai_de_Livraison_jours__c Desc];
    }
    public static TransporteurPrix__c getBestTransporteurMoinsCher(String pays,String orderId){
        Order acc=[Select id,Account.Type_Client__c from Order where Id=:orderId limit 1];
        return [SELECT Name, Tarifs__c, Pays__c,D_lai_de_Livraison_jours__c,Transporteur__r.Name,Transporteur__r.Type_Client__c FROM TransporteurPrix__c WHERE Pays__c = :pays AND Transporteur__r.Type_Client__c INCLUDES(:acc.Account.Type_Client__c) ORDER BY Tarifs__c ASC LIMIT 1];
    }
    public static TransporteurPrix__c getBestTransporteurPlusRapide(String pays,String orderId){
        Order acc=[Select id,Account.Type_Client__c from Order where Id=:orderId limit 1];
        return [SELECT Name, Tarifs__c, Pays__c,D_lai_de_Livraison_jours__c,Transporteur__r.Name,Transporteur__r.Type_Client__c FROM TransporteurPrix__c WHERE Pays__c = :pays AND Transporteur__r.Type_Client__c INCLUDES(:acc.Account.Type_Client__c) ORDER BY D_lai_de_Livraison_jours__c ASC LIMIT 1];
    }
}