force-app/main/default/objects/Livraison__c/Livraison__c.object-meta.xml
<CustomObject>
    <label>Livraison</label>
    <nameField>
        <displayFormat>Livraison-{000000}</displayFormat>
        <label>Numero Livraison</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Livraison</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Livraison__c/fields/D_lai_de_Livraison_jours__c.field-meta.xml
<CustomField>
    <fullName>D_lai_de_Livraison_jours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Délai de Livraison (jours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Livraison</relationshipLabel>
    <relationshipName>Livraison</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays de livraison</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
            <value>
                <fullName>Suisse</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Statut__c.field-meta.xml
<CustomField>
    <fullName>Statut__c</fullName>
    <label>Statut</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>En cours</fullName>
            </value>
            <value>
                <fullName>Livrée</fullName>
            </value>
            <value>
                <fullName>Echouée</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Tarifs__c.field-meta.xml
<CustomField>
    <fullName>Tarifs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Tarifs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Livraison__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Livraison</relationshipLabel>
    <relationshipName>Livraison</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transporteur__c/Transporteur__c.object-meta.xml
<CustomObject>
    <label>Transporteur</label>
    <nameField>
        <label>Transporteur Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transporteur</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/TransporteurPrix__c/TransporteurPrix__c.object-meta.xml
<CustomObject>
    <label>Transporteur Prix</label>
    <nameField>
        <displayFormat>TP-{0000}</displayFormat>
        <label>TransporteurPrix Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transporteur Prix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TransporteurPrix__c/fields/D_lai_de_Livraison_jours__c.field-meta.xml
<CustomField>
    <fullName>D_lai_de_Livraison_jours__c</fullName>
    <label>Délai de Livraison (jours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TransporteurPrix__c/fields/Pays__c.field-meta.xml
<CustomField>
    <fullName>Pays__c</fullName>
    <label>Pays</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Belgique</fullName>
            </value>
            <value>
                <fullName>Suisse</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransporteurPrix__c/fields/Tarifs__c.field-meta.xml
<CustomField>
    <fullName>Tarifs__c</fullName>
    <label>Tarifs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TransporteurPrix__c/fields/Transporteur__c.field-meta.xml
<CustomField>
    <fullName>Transporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transporteur</label>
    <referenceTo>Transporteur__c</referenceTo>
    <relationshipLabel>Transporteur Prix</relationshipLabel>
    <relationshipName>Transporteur_Prix</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TransporteurController.cls
public with sharing class TransporteurController {

    @AuraEnabled(cacheable=true)
    public static Transporteur__c getTransporteur(String pays, String critere){
        return TransporteurService.getBestTransporteur(pays, critere);
    }
     @AuraEnabled(cacheable=true)
    public static TransporteurPrix__c getBestTransporteurMoinsCher(String pays,String orderId){
        return TransporteurService.getBestTransporteurMoinsCher(pays,orderId);
    }
     @AuraEnabled(cacheable=true)
    public static TransporteurPrix__c getBestTransporteurPlusRapide(String pays,String orderId){
        return TransporteurService.getBestTransporteurPlusRapide(pays,orderId);
    }
    @AuraEnabled(cacheable=true)
    public static list<TransporteurPrix__c> getAllTransporteurs(String pays,String orderId){
        return TransporteurService.getAllTransporteurs(pays,orderId);
    }
    @AuraEnabled
public static void updateOrderTransporteur(String orderId, TransporteurPrix__c transporteurPrix){
    /*Order o = new Order(
        Id = orderId,
        Transporteur__c = transporteurPrix.Transporteur__r.Name
    );
    update o;*/
    list<Livraison__c> lvr=[Select id from Livraison__c where Order__c = :orderId limit 1];
    Livraison__c tmpLvr;
    if(lvr.size() > 0){
        tmpLvr = lvr[0];
        tmpLvr.Order__c=orderId;
        tmpLvr.Pays__c=transporteurPrix.Pays__c;
        tmpLvr.Statut__c='En cours';
        tmpLvr.Tarifs__c=transporteurPrix.Tarifs__c;
        tmpLvr.Transporteur__c=transporteurPrix.Transporteur__c;
        tmpLvr.D_lai_de_Livraison_jours__c=transporteurPrix.D_lai_de_Livraison_jours__c;
        update tmpLvr;
    }else{
        tmpLvr=new Livraison__c();
        tmpLvr.Order__c=orderId;
        tmpLvr.Pays__c=transporteurPrix.Pays__c;
        tmpLvr.Statut__c='En cours';
        tmpLvr.Tarifs__c=transporteurPrix.Tarifs__c;
        tmpLvr.Transporteur__c=transporteurPrix.Transporteur__c;
        tmpLvr.D_lai_de_Livraison_jours__c=transporteurPrix.D_lai_de_Livraison_jours__c;
        insert tmpLvr;
    }


}
}